In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('survey_results.csv')
df

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89179,89180,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89180,89181,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
89181,89182,I agree,I code primarily as a hobby,Prefer not to say,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Hackathons (virtual or ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89182,89183,I agree,I am a developer by profession,Under 18 years old,"Employed, part-time;Student, part-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
89183,89184,I agree,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,...,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN

In [3]:
df.columns

Index(['ResponseId', 'Q120', 'MainBranch', 'Age', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'TechList', 'BuyNewTool', 'Country',
       'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysPersonal use',
       'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith',
       'OfficeStackAsyncWantToWorkWith', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'AISearchHaveWorkedWith',
       'AISearchWantToWorkWith', 'AIDevHaveWorkedWith', 'AIDevWantToWorkWith',
       'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOComm',
       'SOAI', 'AISelect', 'AISent', 'AIAcc', 'AIBen',
       'AIToolInterested in Using', 'AIToolCurrently Using',
       'AIToolNot interested in Using', 'AINextVery different',
       'AINextNeither different nor similar', 'AINextSomewhat similar',
       'AINextVery similar', 'AINextSomewhat different', 'TBranch', 'ICorPM',
       'WorkExp', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4',
       'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Knowledge_8',
       'Frequency_1', 'Frequency_2', 'Frequency_3', 'TimeSearching',
       'TimeAnswering', 'ProfessionalTech', 'Industry', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [4]:
df['ConvertedCompYearly'].min()

np.float64(1.0)

In [5]:
df['ConvertedCompYearly'].max()

np.float64(74351432.0)

In [6]:
df['ConvertedCompYearly'].mean()

np.float64(103110.08171765343)

In [7]:
df['ConvertedCompYearly'].std()

np.float64(681418.8387120209)

In [8]:
df['ConvertedCompYearly'].agg(['min', 'max', 'mean', 'median'])

min       1.000000e+00
max       7.435143e+07
mean      1.031101e+05
median    7.496300e+04
Name: ConvertedCompYearly, dtype: float64

In [9]:
df['ConvertedCompYearly'].value_counts() #frequency

ConvertedCompYearly
64254.0     784
53545.0     615
150000.0    585
200000.0    558
74963.0     557
           ...
7336.0        1
34660.0       1
1606.0        1
319711.0      1
16917.0       1
Name: count, Length: 8784, dtype: int64

In [11]:
df['ConvertedCompYearly'].count() #count of non NA values

np.int64(48019)

In [12]:
df['ConvertedCompYearly'].nunique() #count of unique values

8784

In [13]:
df['ConvertedCompYearly'].unique() #unique values

array([    nan, 285000., 250000., ...,   1606., 319711.,  16917.],
      shape=(8785,))

In [16]:
c_groups = df.groupby(df['Country'])
type(c_groups)

pandas.core.groupby.generic.DataFrameGroupBy

In [19]:
india = c_groups.get_group('India').loc[:, ['Age', 'Country', 'YearsCode', 'LanguageHaveWorkedWith', 'Employment']]
india

,Age,Country,YearsCode,LanguageHaveWorkedWith,Employment
9,25-34 years old,India,6,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,"Not employed, but looking for work"
66,25-34 years old,India,10,Java;Scala;SQL,"Employed, full-time"
78,18-24 years old,India,5,JavaScript;TypeScript,"Employed, full-time"
82,25-34 years old,India,10,C++,"Employed, full-time"
85,25-34 years old,India,7,Assembly;C;C++;Java;JavaScript;SQL,"Employed, full-time"
...,...,...,...,...,...
89119,18-24 years old,India,3,Dart;HTML/CSS;JavaScript;Python,"Student, full-time;Employed, part-time"
89121,18-24 years old,India,4,Python;SQL,"Employed, full-time;Student, part-time"
89164,18-24 years old,India,6,Go;HTML/CSS;Java;JavaScript;Python,"Employed, full-time"
89165,25-34 years old,India,6,C;C#;C++;Java;JavaScript;TypeScript,"Employed, full-time"
89167,18-24 years old,India,6,Dart;HTML/CSS;JavaScript;TypeScript,"Employed, full-time"

In [20]:
c_groups['ConvertedCompYearly'].value_counts()

Country      ConvertedCompYearly
Afghanistan  33.0                   1
             41.0                   1
             48.0                   1
             648.0                  1
             794.0                  1
                                   ..
Zimbabwe     7800.0                 1
             10000.0                1
             30000.0                1
             60000.0                1
             114000.0               1
Name: count, Length: 12630, dtype: int64

In [21]:
c_groups['ConvertedCompYearly'].agg(['min', 'max', 'mean', 'median'])

,min,max,mean,median
Country,,,,
Afghanistan,33.0,9203683.0,843636.090909,915.0
Albania,14.0,139700.0,29219.450000,10741.0
Algeria,512.0,37776.0,10069.190476,8782.0
Andorra,23560.0,289142.0,120368.800000,42836.0
Angola,662.0,7942.0,4302.000000,4302.0
...,...,...,...,...
"Venezuela, Bolivarian Republic of...",5.0,180000.0,23068.851852,12000.0
Viet Nam,1.0,125000.0,20995.956140,12763.0
Yemen,1500.0,59917.0,15089.333333,6500.0
Zambia,605.0,41122.0,13897.800000,9687.0
Zimbabwe,3000.0,114000.0,26740.000000,12500.0